name: Run Tests

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Run containers
      run: docker-compose -f docker/docker-compose.yaml up --abort-on-container-exit